'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reports

    '''<summary>
    '''MessagePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessagePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MessageLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblTotalStudents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalStudents As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalCourses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalCourses As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalEnrollments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalEnrollments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAvgEnrollments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvgEnrollments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMostPopularCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMostPopularCourse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEnrollmentRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnrollmentRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExportData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportData As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chartContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''noDataMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noDataMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''trendsChartContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trendsChartContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlNoTrendsData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoTrendsData As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''formatChartContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formatChartContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlNoFormatData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoFormatData As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rpRecentActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpRecentActivity As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlNoActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoActivity As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hdnCourseNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCourseNames As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnStudentCounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStudentCounts As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnTrendMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTrendMonths As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnTrendEnrollments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTrendEnrollments As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnFormatLabels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFormatLabels As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnFormatCounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFormatCounts As Global.System.Web.UI.WebControls.HiddenField
End Class
